config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  get 'books' => 'books#index'

  post 'books' => 'books#create'

  get 'books/:id' => 'books#show', as: 'book'

  get 'books/:id/edit' => 'books#edit', as: 'edit_book'

  patch 'books/:id' => 'books#update', as: 'update_book'

  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    @books = Book.all
    @new_book = Book.new
  end
  
  def create
    book = Book.new(book_params)
      if book.save
         flash[:success] = 'Book was successfully created.'
         redirect_to book_path(book.id)
      else
        @books = Book.all
        @new_book = book
        render :index
      end
    
  end
  
  def show
    @show_book = Book.find(params[:id])
  end

  def edit
    @edit_book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
       flash[:success] = 'Book was successfully updated.'
       redirect_to book_path(book.id)
    else
       @books = Book.all
       @new_book = book
       render :index
    end
  end
  
  def  destroy
    book = Book.find(params[:id]) 
    book.destroy
    redirect_to '/books'
  end
    
  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookers_helper.rb
module BookersHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<body>

<h1>Editing Book</h1>

 <%= form_with model: @edit_book ,url: update_book_path(@edit_book.id), method: :patch do |f| %>
 
 <div class="field">
  <h4>Title</h4>
  <%= f.text_field :title %>
 </div>
 
 <div class="field">
  <h4>Body</h4>
  <%= f.text_area :body %>
 </div>

 <div class="actions">
  <%= f.submit 'Update Book' %>
 </div>
 
  <%= link_to "Show", book_path(@edit_book.id) %> | <%= link_to "Back", books_path %>

  <% end %>

</body>

app/views/books/index.html.erb
<body>
  <p id="notice"></p>
  <h1>Books</h1>

 <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colospan="3"></th>
    </tr>
  </thead>

  <tbody>

 <% @books.each do |book| %>
    <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book.id)%></td>
        <td><%= link_to "Edit", edit_book_path(book.id)%></td>
        <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
<% end %>
  </tbody>
 </table>

  <h2>New book</h2>

  <% if @new_book.errors.any? %>
    <%= @new_book.errors.count %>errors prohibited this book from being saved: %>
      <ul>
      <% @new_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>

  <%= form_with model: @new_book ,url: books_path, method: :post do |f| %>

  <div>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>

    <%=f.submit 'Create Book' %>

  <% end %>
  </div>
 </body>

app/views/books/new.html.erb
<h1>New book</h1>

<%= form_with model: @books,url:'/books', method: :post do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Body</h4>
  <%= f.text_area :body %>
  
  <%= f.submit 'Create Book' %>
  
<% end %>

app/views/books/show.html.erb
<body>

<p id = "notice"></p>

<p>
  <strong>Title</strong>
  <%= @show_book.title %>
</p>
  

<p>
  <strong>Body</strong>
  <%= @show_book.body %>
</p>

<%= link_to "Edit", edit_book_path(@show_book.id) %> | 
<%= link_to "Back", books_path %>

</body>

app/views/homes/top.html.erb
<h1>ようこそ
  <strong>Bookers</strong>へ!
</h1>

<p><strong>Bookers</strong>"では、様々な書籍に関するあなたの意見や"</p>

<p>印象を共有し交換することができます</p>

<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>
    <%= yield %>
  </body>
</html>